---
name: Build and Test Docker Image

"on":
    workflow_call:
        inputs:
            docker-tag:
                description: 'Docker image tag'
                required: false
                type: string
                default: 'test'

env:
    DOCKER_TAG: ${{ inputs.docker-tag }}

jobs:
    docker:
        name: Build and Test Docker Image
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/Blocksize-Capital-GmbH/supraexporter
                  tags: |
                      type=raw,value=latest,enable=${{ inputs.build-type == 'main' && github.ref == 'refs/heads/main' }}
                      type=sha,format=long
                      type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
                      type=raw,value=develop-${{ inputs.branch-name }},enable=${{ inputs.build-type == 'branch' }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Set Package Visibility to Public
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  PACKAGE_NAME="supraexporter"
                  OWNER="Blocksize-Capital-GmbH"

                  echo "Attempting to set package visibility to public..."
                  response=$(curl -s -w "%{http_code}" -X PATCH \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      https://api.github.com/orgs/$OWNER/packages/container/$PACKAGE_NAME \
                      -d '{"visibility":"public"}')

                  http_code="${response: -3}"
                  if [ "$http_code" = "200" ] || [ "$http_code" = "204" ]; then
                      echo "✅ Package visibility set to public successfully"
                  else
                      echo "⚠️ Failed to set package visibility (HTTP $http_code)"
                      echo "This might be due to permissions or the package not existing yet"
                      echo "Continuing anyway as this is not critical for the build"
                  fi
