---
name: Build and Test Docker Image

on:
    workflow_call:
    push:
        branches:
            - main
        tags:
            - v*
    workflow_dispatch:

env:
    DOCKER_TAG: ${{ inputs.docker-tag }}

jobs:
    docker:
        name: Build and Test Docker Image
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker Image
              run: |
                  docker build \
                  -t ghcr.io/blocksize-capital-gmbh/supraexporter:latest \
                  -t ghcr.io/blocksize-capital-gmbh/supraexporter:${{ github.sha }} \
                  -f ./Dockerfile .

            - name: Push Docker Image
              run: |
                  docker push ghcr.io/blocksize-capital-gmbh/supraexporter:latest
                  docker push ghcr.io/blocksize-capital-gmbh/supraexporter:${{ github.sha }}

            - name: Set Package Visibility to Public
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  PACKAGE_NAME="supraexporter"
                  OWNER="blocksize-capital-gmbh"
                  curl -X PATCH \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer $GITHUB_TOKEN" \
                      https://api.github.com/orgs/$OWNER/packages/container/$PACKAGE_NAME \
                      -d '{"visibility":"public"}'
