---
name: Build and Test Docker Image

"on":
    workflow_call:
        inputs:
            docker-tag:
                description: 'Docker image tag'
                required: false
                type: string
                default: 'test'

env:
    DOCKER_TAG: ${{ inputs.docker-tag }}

jobs:
    docker:
        name: Build and Test Docker Image
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: |
                  docker build -t supraexporter:${{ env.DOCKER_TAG }} .

            - name: Test Docker image functionality
              run: >-
                  docker run --rm supraexporter:${{ env.DOCKER_TAG }} python -c
                  "import supraexporter; print('Docker build successful')"
