name: Docstring Check

on:
    workflow_call:

jobs:
    check-docstring:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Install Dependencies
              run: |
                  pip install poetry
                  poetry install -vv --no-root

            - name: Run Docstring Checks
              run: |
                  poetry run pydocstyle supraexporter/
