---
name: Check Documentation Strings

"on":
    workflow_call:
        inputs:
            python-version:
                description: 'Python version to use'
                required: false
                type: string
                default: '3.12'
            artifacts-dir:
                description: 'Directory for storing all artifacts'
                required: false
                type: string
                default: 'artifacts'

env:
    PYTHON_VERSION: ${{ inputs.python-version }}
    ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}

jobs:
    docstring-check:
        name: Check Documentation Strings
        runs-on: ubuntu-22.04
        continue-on-error: true
        steps:
            - name: Download unified artifacts
              uses: actions/download-artifact@v4
              with:
                  name: supraexporter-artifacts-${{ github.run_id }}
                  path: ${{ env.ARTIFACTS_DIR }}

            - name: Copy .github directory to workspace root
              run: |
                  set -e
                  echo "=== Debugging artifacts structure ==="
                  ARTIFACTS_PATH="${{ env.ARTIFACTS_DIR }}"
                  echo "Artifacts directory: $ARTIFACTS_PATH"
                  echo "Current working directory: $(pwd)"
                  echo "Workspace: $GITHUB_WORKSPACE"
                  
                  echo "Contents of artifacts directory:"
                  ls -la "$ARTIFACTS_PATH" || echo "Artifacts directory not found"
                  
                  echo "Contents of artifacts/source:"
                  ls -la "$ARTIFACTS_PATH/source" || echo "Source directory not found"
                  
                  echo "Looking for .github directory:"
                  if [ -d "$ARTIFACTS_PATH/source/.github" ]; then
                      echo "✓ Found .github directory at $ARTIFACTS_PATH/source/.github"
                      echo "Contents:"
                      ls -la "$ARTIFACTS_PATH/source/.github"
                      
                      echo "Copying .github directory to workspace root..."
                      cp -r "$ARTIFACTS_PATH/source/.github" "$GITHUB_WORKSPACE/"
                      echo "✓ .github directory copied successfully"
                  else
                      echo "✗ .github directory not found in artifacts"
                      echo "Searching for .github in artifacts..."
                      find "$ARTIFACTS_PATH" -name ".github" -type d 2>/dev/null || echo "No .github directory found"
                      
                      echo "This is unexpected - creating minimal .github structure for action to work"
                      mkdir -p "$GITHUB_WORKSPACE/.github/actions/restore-environment"
                      echo "Minimal .github structure created as fallback"
                  fi

            - name: Restore Environment
              uses: ./.github/actions/restore-environment
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
                  artifacts-dir: ${{ env.ARTIFACTS_DIR }}

            - name: Run docstring style checks via pre-commit
              run: |
                  source "${{ env.ARTIFACTS_DIR }}/python-env.sh"
                  cd "$PROJECT_DIR"
                  
                  # Execute docstring checks via poetry (reproducing local workflow)
                  poetry run pydocstyle supraexporter/
