---
name: Run Code Linting

"on":
    workflow_call:
        inputs:
            python-version:
                description: 'Python version to use'
                required: false
                type: string
                default: '3.12'
            artifacts-dir:
                description: 'Directory for storing all artifacts'
                required: false
                type: string
                default: 'artifacts'

env:
    PYTHON_VERSION: ${{ inputs.python-version }}
    ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}

jobs:
    lint:
        name: Run Code Linting
        runs-on: ubuntu-22.04
        steps:
            - name: Restore Environment
              uses: ./.github/actions/restore-environment
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
                  artifacts-dir: ${{ env.ARTIFACTS_DIR }}

            - name: Run linting checks via pre-commit
              run: |
                  source "${{ env.ARTIFACTS_DIR }}/python-env.sh"
                  cd "$PROJECT_DIR"
                  
                  # Execute linting checks via pre-commit (reproducing local workflow)
                  poetry run pre-commit run flake8 --all-files
                  poetry run pre-commit run codespell --all-files
