name: Lint

on:
    workflow_call:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Install deps
              uses: ./.github/workflows/install.yml

            - name: Run Linting
              run: |
                  poetry run pre-commit run black --all-files
                  poetry run pre-commit run isort --all-files
                  poetry run pre-commit run flake8 --all-files
                  poetry run pre-commit run codespell --all-files
