---
name: CI Pipeline

on:
    push:
        branches:
            - main
            - develop
            - "feature/*"
            - "hotfix/*"
            # Temporarily removed "bug-fixes" to prevent dual triggers while PR #4 is open
            # Will re-add after PR is merged or closed
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

permissions:
    packages: write
    contents: read
    actions: read
    security-events: write

env:
    PYTHON_VERSION: "3.12"
    ARTIFACTS_DIR: "artifacts"

jobs:
    # ===========================================
    # MAIN BRANCH WORKFLOW (Comprehensive)
    # ===========================================
    main_branch_ci:
        name: Main Branch CI
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: ./.github/workflows/main-branch-ci.yml
        with:
            python-version: "3.12"
            artifacts-dir: "artifacts"

    # ===========================================
    # FEATURE BRANCH WORKFLOW (Fast feedback)
    # ===========================================
    feature_branch_ci:
        name: Feature Branch CI
        if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
        uses: ./.github/workflows/feature-branch-ci.yml
        with:
            python-version: "3.12"
            artifacts-dir: "artifacts"
            branch-name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

    # ===========================================
    # FINAL STATUS CHECK
    # ===========================================
    ci_success:
        name: CI Pipeline Success
        runs-on: ubuntu-22.04
        if: always()
        needs: [main_branch_ci, feature_branch_ci]
        steps:
            - name: Check CI status
              run: |
                  # Check which workflow ran and its result
                  if [[ "${{ needs.main_branch_ci.result }}" != "skipped" ]]; then
                      WORKFLOW_RESULT="${{ needs.main_branch_ci.result }}"
                      WORKFLOW_NAME="Main Branch CI"
                  elif [[ "${{ needs.feature_branch_ci.result }}" != "skipped" ]]; then
                      WORKFLOW_RESULT="${{ needs.feature_branch_ci.result }}"
                      WORKFLOW_NAME="Feature Branch CI"
                  else
                      echo "❌ No workflow executed"
                      exit 1
                  fi

                  # Report the result
                  case "$WORKFLOW_RESULT" in
                      "success")
                          echo "✅ $WORKFLOW_NAME completed successfully"
                          ;;
                      "failure")
                          echo "❌ $WORKFLOW_NAME failed"
                          exit 1
                          ;;
                      "cancelled")
                          echo "⚠️ $WORKFLOW_NAME was cancelled"
                          exit 1
                          ;;
                      *)
                          echo "❓ $WORKFLOW_NAME result: $WORKFLOW_RESULT"
                          exit 1
                          ;;
                  esac
