name: CI Pipeline

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

permissions:
    packages: write
    contents: read

jobs:
    linting:
        name: linting
        runs-on: ubuntu-latest
        steps:
            install:
                uses: ./.github/workflows/install.yml
            lint:
                uses: ./.github/workflows/lint.yml

    format:
        uses: ./.github/workflows/format.yml

    run-tests:
        uses: ./.github/workflows/tests.yml

    check-docstring:
        uses: ./.github/workflows/docstring-check.yml

    type-check:
        uses: ./.github/workflows/type-check.yml

    docker:
        uses: ./.github/workflows/docker.yml
