---
name: Run Tests

"on":
    workflow_call:
        inputs:
            python-version:
                description: 'Python version to use'
                required: false
                type: string
                default: '3.12'
            artifacts-dir:
                description: 'Directory for storing all artifacts'
                required: false
                type: string
                default: '/home/runner/work/artifacts'

env:
    PYTHON_VERSION: ${{ inputs.python-version }}
    ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}

jobs:
    tests:
        name: Run Tests
        runs-on: ubuntu-22.04
        steps:
            - name: Restore Environment
              uses: ./.github/actions/restore-environment
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
                  artifacts-dir: ${{ env.ARTIFACTS_DIR }}

            - name: Run test suite with coverage
              run: |
                  source "${{ env.ARTIFACTS_DIR }}/python-env.sh"
                  cd "$PROJECT_DIR"
                  
                  # Execute tests via poetry (reproducing local workflow)
                  poetry run pytest supraexporter/tests/ -v \
                      --cov=supraexporter --cov-report=html --cov-report=term-missing

            - name: Upload coverage reports
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report-${{ github.run_id }}
                  path: ${{ env.ARTIFACTS_DIR }}/source/htmlcov/
                  retention-days: 7
