---
name: Run Type Checking

"on":
    workflow_call:
        inputs:
            python-version:
                description: 'Python version to use'
                required: false
                type: string
                default: '3.12'
            artifacts-dir:
                description: 'Directory for storing all artifacts'
                required: false
                type: string
                default: 'artifacts'

env:
    PYTHON_VERSION: ${{ inputs.python-version }}
    ARTIFACTS_DIR: ${{ inputs.artifacts-dir }}

jobs:
    type-check:
        name: Run Type Checking
        runs-on: ubuntu-22.04
        continue-on-error: true
        steps:
            - name: Download unified artifacts
              uses: actions/download-artifact@v4
              with:
                  name: supraexporter-artifacts-${{ github.run_id }}
                  path: ${{ env.ARTIFACTS_DIR }}

            - name: Copy .github directory to workspace root
              run: |
                  # Copy .github directory from artifacts to workspace root for local action access
                  cp -r "${{ env.ARTIFACTS_DIR }}/source/.github" .
                  echo "Copied .github directory to workspace root"

            - name: Restore Environment
              uses: ./.github/actions/restore-environment
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
                  artifacts-dir: ${{ env.ARTIFACTS_DIR }}

            - name: Run static type checking via pre-commit
              run: |
                  source "${{ env.ARTIFACTS_DIR }}/python-env.sh"
                  cd "$PROJECT_DIR"
                  
                  # Execute type checking via poetry (reproducing local workflow)
                  poetry run mypy --ignore-missing-imports supraexporter/
