name: Type Checking

on:
    workflow_call:

jobs:
    type-check:
        name: Type Checking
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Install Dependencies
              run: |
                  pip install poetry
                  poetry install -vv

            - name: Run Type Checks
              run: |
                  poetry run mypy --ignore-missing-imports solanaexporter/
